// Renders site/index.html — the public browse page for the bank — from
// data/protocols/*.json. Deterministic; regenerated by generate-index.mjs and
// drift-checked by validate.mjs:
//
//   node packages/protocol-bank/scripts/generate-index.mjs
//
// Layout is master-detail: the left column scans, the right column holds one
// full protocol. The list opens with an opinionated Start here set, because
// 227 rows is not a browsable thing on its own.
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

// Two vocabularies. Short for the filter chips, where space is scarce and the
// icon carries meaning. Longer for the list headings, where "Starting" and
// "Rhythm" on their own do not say what they mean.
const KIND_LONG = {
  priorities: "Priorities",
  decisions: "Decision making",
  starting: "Getting started",
  focus: "Protecting focus",
  rhythm: "Work rhythm",
  ideas: "Ideas and creativity",
  learning: "Learning and craft",
  review: "Review and feedback",
  calendar_defense: "Calendar defense",
  social: "People and feedback",
  sleep: "Sleep",
  training: "Exercise",
  walk: "Daily movement",
  recovery: "Recovery",
  nutrition: "Nutrition",
};
// Two groups so fifteen chips read as two short lists instead of one long one.
const KIND_GROUP = {
  priorities: "work", decisions: "work", starting: "work", focus: "work",
  rhythm: "work", ideas: "work", learning: "work", review: "work",
  calendar_defense: "work", social: "work",
  sleep: "body", training: "body", walk: "body", recovery: "body", nutrition: "body",
};
const KIND_LABEL = {
  focus: "Focus",
  starting: "Starting",
  rhythm: "Rhythm",
  priorities: "Priorities",
  decisions: "Decisions",
  ideas: "Ideas",
  learning: "Learning",
  review: "Review",
  calendar_defense: "Calendar",
  sleep: "Sleep",
  training: "Exercise",
  recovery: "Recovery",
  nutrition: "Nutrition",
  walk: "Movement",
  social: "People",
};
// How a workday actually runs: choose the work, start it, hold it, pace it,
// then learn from it. Body and calendar underneath.
const KIND_ORDER = [
  "priorities",
  "decisions",
  "starting",
  "focus",
  "rhythm",
  "ideas",
  "learning",
  "review",
  "calendar_defense",
  "sleep",
  "training",
  "recovery",
  "nutrition",
  "walk",
  "social",
];
const FAMILY_LABEL = {
  attention_defense: "Focus defense",
  daily_activity: "Daily activity",
  aerobic_volume: "Aerobic volume",
  strength_capacity: "Strength",
  sleep_regularity: "Sleep rhythm",
  sleep_shutdown: "Screen shutdown",
  calendar_defense: "Calendar defense",
  meal_timing: "Meal timing",
  eating_window: "Eating window",
  heat_exposure: "Heat exposure",
  cold_exposure: "Cold exposure",
  mindfulness: "Mindfulness",
};
const TIER_ORDER = { beginner: 0, intermediate: 1, advanced: 2 };
const GRADE_STEPS = { strong: 4, moderate: 3, emerging: 2, anecdotal: 1 };
const GRADES = ["strong", "moderate", "emerging", "anecdotal"];
// An opinionated starting set. 227 is too many to walk cold, so the list opens
// with the handful worth running first. Edit this line to change the opinion.
const ESSENTIALS = [
  "morning_light",
  "caffeine_cutoff",
  "screen_shutdown",
  "wind_down",
  "walk_reset",
  "zone2_aerobic",
  "strength_training",
];

const esc = (s) =>
  String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");

// Inline stroke icons, one per area. Drawn at 24 and scaled down, so the
// filter row reads as a set of objects rather than a row of word-pills.
const svg = (body) =>
  `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const ICONS = {
  // crosshair: holding one thing in view
  focus: svg('<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3.2"/><path d="M12 1.6v2.6M12 19.8v2.6M22.4 12h-2.6M4.2 12H1.6"/>'),
  // play: the first move
  starting: svg('<circle cx="12" cy="12" r="9"/><path d="M10 8.6l6 3.4-6 3.4Z"/>'),
  // waveform: the beat of the day
  rhythm: svg('<path d="M2.4 12h3l2.4-6.4 3.6 13L15 8.4l1.8 3.6h4.8"/>'),
  // stacked bars, tallest first: what matters most
  priorities: svg('<path d="M4 20V7.6M10 20v-9M16 20v-5.4M22 20H2"/>'),
  // fork in the road
  decisions: svg('<path d="M12 21.4V13m0 0L5.6 6.6M12 13l6.4-6.4"/><path d="M3 3.2h4v4M21 3.2h-4v4"/>'),
  // lightbulb
  ideas: svg('<path d="M9.4 18.4h5.2M10.2 21.4h3.6"/><path d="M12 2.6a6.4 6.4 0 0 0-3.8 11.5c.6.5 1 1.2 1 2h5.6c0-.8.4-1.5 1-2A6.4 6.4 0 0 0 12 2.6Z"/>'),
  // open book
  learning: svg('<path d="M12 6.4v14"/><path d="M12 6.4C10.4 4.9 8.2 4.2 5 4.2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1c3.2 0 5.4.7 7 2.2 1.6-1.5 3.8-2.2 7-2.2a1 1 0 0 0 1-1v-12a1 1 0 0 0-1-1c-3.2 0-5.4.7-7 2.2Z"/>'),
  // loop back
  review: svg('<path d="M3.2 12a8.8 8.8 0 1 1 2.9 6.5"/><path d="M2.6 19.6v-5h5"/>'),
  calendar_defense: svg('<rect x="3.2" y="5" width="17.6" height="16" rx="2.4"/><path d="M3.2 10h17.6M8 2.8v4.4M16 2.8v4.4"/>'),
  sleep: svg('<path d="M20.5 14.6A8.6 8.6 0 1 1 9.4 3.5a6.9 6.9 0 0 0 11.1 11.1Z"/>'),
  training: svg('<path d="M2.6 9.4v5.2M6 7v10M18 7v10M21.4 9.4v5.2M6 12h12"/>'),
  recovery: svg('<path d="M20.3 5.6a5 5 0 0 0-7.1 0L12 6.8l-1.2-1.2a5 5 0 1 0-7.1 7.1L12 21l8.3-8.3a5 5 0 0 0 0-7.1Z"/>'),
  nutrition: svg('<path d="M12 7.6c-1.8-3-6-3-7.6 0-1.6 3 .6 9.4 3.6 12.2 1.2 1.1 2.8.4 4-.4 1.2.8 2.8 1.5 4 .4 3-2.8 5.2-9.2 3.6-12.2-1.6-3-5.8-3-7.6 0Z"/><path d="M12 7.6V4.4a2.8 2.8 0 0 1 2.8-2.8"/>'),
  walk: svg('<circle cx="13.4" cy="3.9" r="2"/><path d="M11 21.6l1.8-6-3-2.6.9-5 3.4 2.2 3 1.4M9.4 21.6l1.6-4.4M17.6 21.6l-2-5.4"/>'),
  social: svg('<circle cx="9" cy="8.4" r="3.4"/><path d="M2.8 20.4a6.2 6.2 0 0 1 12.4 0"/><path d="M16.4 5.4a3.4 3.4 0 0 1 0 6M17.8 14.8a6.2 6.2 0 0 1 3.4 5.6"/>'),
};
const STAR_ICON = svg('<path d="M12 3.2l2.6 5.6 6 .8-4.4 4.2 1.1 6.1-5.3-2.9-5.3 2.9 1.1-6.1L3.4 9.6l6-.8Z"/>');
const GH_ICON =
  '<svg viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/></svg>';

// Say the grade in words. A bar chart of four segments looked like a signal
// meter and did not tell anyone what it measured.
const gradeTag = (grade) =>
  `<span class="tag" data-grade="${grade}"><i></i>${grade}</span>`;

export async function renderSite() {
  const dataDir = path.join(pkgRoot, "data", "protocols");
  const files = (await readdir(dataDir)).filter((f) => f.endsWith(".json")).sort();
  const protocols = [];
  for (const file of files) {
    protocols.push(JSON.parse(await readFile(path.join(dataDir, file), "utf8")));
  }

  const counts = { strong: 0, moderate: 0, emerging: 0, anecdotal: 0 };
  for (const p of protocols) counts[p.evidence.grade]++;

  // Ladder rungs, so a detail pane can show where a protocol sits.
  const ladders = new Map();
  for (const p of protocols) {
    if (!p.family) continue;
    if (!ladders.has(p.family)) ladders.set(p.family, []);
    ladders.get(p.family).push(p);
  }
  for (const rungs of ladders.values()) rungs.sort((a, b) => TIER_ORDER[a.tier] - TIER_ORDER[b.tier]);

  const byKind = new Map();
  for (const p of protocols) {
    if (!byKind.has(p.kind)) byKind.set(p.kind, []);
    byKind.get(p.kind).push(p);
  }
  const kinds = KIND_ORDER.filter((k) => byKind.has(k));
  for (const k of byKind.keys()) if (!kinds.includes(k)) kinds.push(k);
  for (const list of byKind.values()) {
    list.sort(
      (a, b) =>
        GRADE_STEPS[b.evidence.grade] - GRADE_STEPS[a.evidence.grade] ||
        a.name.localeCompare(b.name),
    );
  }

  const hay = (p) =>
    esc(
      [p.id, p.name, p.title, p.benefit, p.rationale, p.origin ?? "", ...p.targets, ...p.indications]
        .join(" ")
        .toLowerCase(),
    );

  // One line per protocol: what it is called, and how well supported it is.
  // Everything else lives in the panel, so 227 stays scannable.
  const row = (p) => `
      <button class="row" role="option" id="r-${esc(p.id)}" data-id="${esc(p.id)}" data-grade="${p.evidence.grade}" data-kind="${esc(p.kind)}"${ESSENTIALS.includes(p.id) ? ' data-essential="1"' : ""} data-hay="${hay(p)}">
        <span class="row-name">${esc(p.name)}</span>
        ${gradeTag(p.evidence.grade)}
      </button>`;

  const ladderStrip = (p) => {
    if (!p.family) return "";
    const rungs = ladders.get(p.family) ?? [];
    return `
        <div class="ladder">
          <span class="lab">${esc(FAMILY_LABEL[p.family] ?? p.family)} ladder</span>
          <div class="rungs">
            ${rungs
              .map(
                (r) =>
                  `<button class="rung ${r.id === p.id ? "here" : ""}" data-goto="${esc(r.id)}">
                     <span class="rung-tier">${esc(r.tier)}</span>
                     <span class="rung-bar">${esc(r.tierTarget)}</span>
                   </button>`,
              )
              .join("")}
          </div>
        </div>`;
  };

  // One pattern all the way down: a short hero, then labelled blocks. Nothing
  // free-floating below the hero, so the panel reads as one system.
  const block = (label, body) => `<section class="d-block"><h3>${label}</h3>${body}</section>`;
  const bullets = (items) => `<ul>${items.map((i) => `<li>${esc(i)}</li>`).join("")}</ul>`;

  const detail = (p) => `
      <article class="detail" id="d-${esc(p.id)}" hidden>
        <header class="d-head">
          ${gradeTag(p.evidence.grade)}
          <span class="d-kind">${ICONS[p.kind] ?? ""}${esc(KIND_LABEL[p.kind] ?? p.kind)}</span>
          <button class="d-close" data-close aria-label="Back to the list">Back</button>
        </header>
        <h2>${esc(p.name)}</h2>
        <p class="d-do">${esc(p.title)}</p>
        <p class="d-benefit">${esc(p.benefit)}</p>
        ${p.origin ? `<p class="d-origin">${esc(p.origin)}</p>` : ""}
        ${block("Try it when", bullets(p.indications))}
        ${block("Why it works", `<p>${esc(p.rationale)}</p>`)}
        ${p.avoidWhen ? `<section class="d-block avoid"><h3>Skip it when</h3>${bullets(p.avoidWhen)}</section>` : ""}
        ${ladderStrip(p)}
        ${block(
          "Proof",
          `<p class="d-links">${p.evidence.sources
            .map(
              (s) =>
                `<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)}</a>`,
            )
            .join("")}${
            p.guide
              ? `<a href="${esc(p.guide.url)}" target="_blank" rel="noopener">How to start, via ${esc(p.guide.source)}</a>`
              : ""
          }</p>`,
        )}
      </article>`;

  const list = kinds
      .map(
        (k) => `
      <section class="area" data-kind="${esc(k)}">
        <h2 class="area-head">${ICONS[k] ?? ""}${esc(KIND_LONG[k] ?? KIND_LABEL[k] ?? k)} <span>${byKind.get(k).length}</span></h2>
        ${byKind.get(k).map(row).join("")}
      </section>`,
    )
    .join("");

  const total = protocols.length;
  const dist = GRADES.map(
    (g) =>
      `<i class="seg-${g}" style="flex:${counts[g]}" title="${counts[g]} ${g}"></i>`,
  ).join("");
  const distKey = GRADES.map(
    (g) => `<span class="k"><i class="seg-${g}"></i><b>${counts[g]}</b>${g}</span>`,
  ).join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Productivity Protocols</title>
<meta name="description" content="${protocols.length} behaviors founders and researchers actually use, each with an honest evidence grade, the signals that say try it, and citations.">
<meta property="og:title" content="Productivity Protocols">
<meta property="og:description" content="${protocols.length} behaviors founders and researchers actually use, graded honestly.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://protocols.aescle.com">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&family=Karla:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>
  :root {
    --paper: #faf9f5; --card: #ffffff; --ink: #17181a; --muted: #6b6f6c;
    --faint: #9aa09b; --line: #e6e4dd; --line-soft: #efede7;
    --accent: #16584a; --accent-soft: #e4efea;
    --warn: #8a4b2a;
    --shadow: 0 1px 2px rgba(23,24,26,.04), 0 8px 24px rgba(23,24,26,.05);
    --g-strong: #17795f; --g-moderate: #3d72a4; --g-emerging: #b07219; --g-anecdotal: #9a9a94;
    --display: "Fraunces", Georgia, "Times New Roman", serif;
    --body: "Karla", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    --mono: "IBM Plex Mono", ui-monospace, Menlo, monospace;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --paper: #14161a; --card: #1b1e23; --ink: #eceae4; --muted: #9aa09c;
      --faint: #6d746f; --line: #2a2e34; --line-soft: #23272c;
      --accent: #6fc4ab; --accent-soft: #1c332e;
      --warn: #d59a72;
      --shadow: 0 1px 2px rgba(0,0,0,.3), 0 8px 24px rgba(0,0,0,.28);
      --g-strong: #5cc0a2; --g-moderate: #79a9d8; --g-emerging: #d9a25c; --g-anecdotal: #7d827d;
    }
  }
  :root[data-theme="dark"] {
    --paper: #14161a; --card: #1b1e23; --ink: #eceae4; --muted: #9aa09c;
    --faint: #6d746f; --line: #2a2e34; --line-soft: #23272c;
    --accent: #6fc4ab; --accent-soft: #1c332e;
    --warn: #d59a72;
    --shadow: 0 1px 2px rgba(0,0,0,.3), 0 8px 24px rgba(0,0,0,.28);
    --g-strong: #5cc0a2; --g-moderate: #79a9d8; --g-emerging: #d9a25c; --g-anecdotal: #7d827d;
  }

  * { box-sizing: border-box; }
  html { -webkit-text-size-adjust: 100%; }
  body {
    margin: 0; background: var(--paper); color: var(--ink);
    font-family: var(--body); font-size: 15px; line-height: 1.55;
    -webkit-font-smoothing: antialiased;
  }
  a { color: inherit; }
  button { font: inherit; color: inherit; background: none; border: 0; cursor: pointer; }
  :focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; border-radius: 4px; }

  .wrap { max-width: 1240px; margin: 0 auto; padding: 0 28px; }
  /* Set from the toolbar's real height on load and resize; the toolbar wraps
     to two rows at narrow widths, so a hardcoded offset clips the panel. */
  :root { --stick: 132px; }

  /* ── owner bar ───────────────────────────────────────────── */
  .owner { border-bottom: 1px solid var(--line); }
  .owner-in {
    min-height: 52px; display: flex; align-items: center; justify-content: space-between;
    gap: 20px; font-size: 13px;
  }
  .owner-mark {
    display: inline-flex; align-items: center; gap: 9px; color: var(--accent);
    text-decoration: none; font-weight: 600;
  }
  .owner-mark svg { width: 19px; height: 19px; flex: 0 0 auto; }
  .owner-mark b { font-size: 11px; letter-spacing: .18em; }
  .owner-cta { color: var(--muted); text-decoration: none; }
  .owner-cta:hover { color: var(--ink); }

  /* ── masthead ─────────────────────────────────────────────── */
  .mast { padding: 68px 0 34px; max-width: 700px; }
  .mast h1 {
    font-family: var(--display); font-optical-sizing: auto;
    font-size: clamp(38px, 6vw, 60px); font-weight: 600; line-height: 1.02;
    letter-spacing: -0.025em; margin: 0 0 20px; text-wrap: balance;
  }
  .mast .lede { font-size: 18px; line-height: 1.5; color: var(--muted); margin: 0 0 30px; max-width: 60ch; text-wrap: pretty; }

  /* Show the mix, do not list four numbers and hope. */
  .evidence-mix { max-width: 460px; }
  .mix-top { font-size: 13.5px; color: var(--muted); margin-bottom: 10px; }
  .mix-top b { font-family: var(--display); font-size: 22px; font-weight: 600; color: var(--ink); letter-spacing: -0.02em; }
  .dist { display: flex; gap: 3px; height: 12px; }
  .dist i { display: block; border-radius: 3px; min-width: 6px; }
  .dist-key { display: flex; flex-wrap: wrap; gap: 6px 16px; margin-top: 10px; }
  .dist-key .k {
    display: inline-flex; align-items: center; gap: 6px;
    font-family: var(--mono); font-size: 11.5px; color: var(--muted);
  }
  .dist-key .k i { width: 8px; height: 8px; border-radius: 2px; flex: 0 0 auto; }
  .dist-key .k b { color: var(--ink); font-weight: 500; }
  .seg-strong { background: var(--g-strong); }
  .seg-moderate { background: var(--g-moderate); }
  .seg-emerging { background: var(--g-emerging); }
  .seg-anecdotal { background: var(--g-anecdotal); }

  .mast .use { display: flex; flex-wrap: wrap; align-items: center; gap: 10px 16px; margin: 28px 0 0; }
  .mast .use code {
    font-family: var(--mono); font-size: 12.5px; background: var(--card);
    border: 1px solid var(--line); border-radius: 7px; padding: 6px 10px; white-space: nowrap;
  }
  .mast .use a {
    display: inline-flex; align-items: center; gap: 6px; font-size: 13.5px;
    color: var(--muted); text-decoration: none;
  }
  .mast .use a:hover { color: var(--ink); }
  .mast .use a svg { width: 15px; height: 15px; flex: 0 0 auto; }
  .mast .use a span { text-decoration: underline; text-underline-offset: 3px; text-decoration-color: var(--line); }

  /* ── toolbar ──────────────────────────────────────────────── */
  .tools {
    position: sticky; top: 0; z-index: 20; background: var(--paper);
    border-bottom: 1px solid var(--line); padding: 14px 0;
  }
  .tools-in { display: flex; flex-wrap: wrap; gap: 14px 18px; align-items: center; }
  .search {
    flex: 1 1 240px; min-width: 190px; padding: 9px 14px; border-radius: 9px;
    border: 1px solid var(--line); background: var(--card); color: var(--ink);
    font: inherit; font-size: 14px;
  }
  .search::placeholder { color: var(--faint); }
  /* Same four words, same four colours, as the meter and the rows. */
  .grades { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; }
  .glabel { font-size: 12.5px; color: var(--muted); margin-right: 2px; white-space: nowrap; }
  .grades button {
    display: inline-flex; align-items: center; gap: 6px;
    font-size: 12.5px; padding: 5px 11px 5px 9px; border-radius: 999px; white-space: nowrap;
    border: 1px solid var(--line); background: var(--card); color: var(--muted);
    transition: border-color .13s, color .13s;
  }
  .grades button i { width: 7px; height: 7px; border-radius: 2px; flex: 0 0 auto; }
  .grades button:hover { color: var(--ink); }
  .grades button[aria-pressed="true"] { border-color: var(--ink); color: var(--ink); }
  .areas { display: flex; flex-direction: column; gap: 6px; width: 100%; }
  .chip-row { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; }
  .grp {
    flex: 0 0 34px;
    font-family: var(--mono); font-size: 10.5px; text-transform: uppercase;
    letter-spacing: 0.09em; color: var(--faint); white-space: nowrap;
  }
  .areas button {
    display: inline-flex; align-items: center; gap: 6px;
    font-size: 12.5px; padding: 5px 10px 5px 8px; border-radius: 999px;
    border: 1px solid var(--line); background: var(--card); color: var(--muted);
    transition: border-color .13s, color .13s, background .13s;
  }
  .areas button svg { width: 13px; height: 13px; flex: 0 0 auto; opacity: .75; }
  .areas button b {
    font-family: var(--mono); font-size: 10.5px; font-weight: 400; color: var(--faint);
    font-variant-numeric: tabular-nums;
  }
  .areas button[aria-pressed="true"] b { color: var(--accent); }
  .areas button:hover { color: var(--ink); }
  .areas button[aria-pressed="true"] { border-color: var(--accent); color: var(--accent); background: var(--accent-soft); }
  .areas button[aria-pressed="true"] svg { opacity: 1; }
  .tally { font-family: var(--mono); font-size: 12px; color: var(--faint); margin-left: auto; white-space: nowrap; }

  /* ── grade tag ────────────────────────────────────────────── */
  .tag {
    display: inline-flex; align-items: center; gap: 6px; flex: 0 0 auto;
    font-family: var(--mono); font-size: 11px; color: var(--muted);
    text-transform: lowercase; letter-spacing: 0.02em;
  }
  .tag i { width: 7px; height: 7px; border-radius: 2px; flex: 0 0 auto; }
  .tag[data-grade="strong"] i { background: var(--g-strong); }
  .tag[data-grade="moderate"] i { background: var(--g-moderate); }
  .tag[data-grade="emerging"] i { background: var(--g-emerging); }
  .tag[data-grade="anecdotal"] i { background: var(--g-anecdotal); }

  /* ── two-pane ─────────────────────────────────────────────── */
  .panes { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1.05fr); gap: 40px; align-items: start; padding: 26px 0 80px; }
  .list { min-width: 0; }
  .area { margin: 0 0 30px; scroll-margin-top: calc(var(--stick) + 8px); }
  .area-head {
    font-family: var(--mono); font-size: 11px; font-weight: 500; text-transform: uppercase;
    letter-spacing: 0.1em; color: var(--faint); margin: 0 0 8px; padding: 0 4px;
    display: flex; align-items: center; gap: 7px;
  }
  .area-head svg { width: 14px; height: 14px; flex: 0 0 auto; }
  .area-head span { color: var(--line); }
  :root[data-theme="dark"] .area-head span { color: var(--muted); }

  .row {
    scroll-margin-top: calc(var(--stick) + 8px);
    display: flex; gap: 14px; width: 100%; text-align: left; align-items: center;
    padding: 9px 13px; border-radius: 9px; border: 1px solid transparent;
    transition: background .12s, border-color .12s;
  }
  .row:hover { background: var(--card); border-color: var(--line-soft); }
  .row[aria-selected="true"] { background: var(--card); border-color: var(--line); box-shadow: var(--shadow); }
  .row-name {
    font-weight: 500; font-size: 14.5px; letter-spacing: -0.005em; flex: 1 1 auto;
    min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  }
  .row .tag { opacity: .8; }
  .row:hover .tag, .row[aria-selected="true"] .tag { opacity: 1; }
  .row.hide, .area.hide { display: none; }

  /* Essentials sits in the same row as the areas and looks the same. It only
     gets a hairline separator, because it filters on a different axis. */
  .areas .is-essential svg { opacity: .9; }

  .empty { padding: 40px 4px; color: var(--muted); font-size: 15px; }
  .empty b { color: var(--ink); font-weight: 600; }

  /* ── detail ───────────────────────────────────────────────── */
  .pane {
    position: sticky; top: var(--stick); background: var(--card); border: 1px solid var(--line);
    border-radius: 16px; padding: 30px 32px; box-shadow: var(--shadow);
    max-height: calc(100vh - var(--stick) - 24px); overflow-y: auto; overscroll-behavior: contain;
  }
  .d-head { display: flex; align-items: center; gap: 9px; margin-bottom: 18px; }
  .d-grade, .d-kind {
    font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.07em;
    color: var(--faint);
  }
  .d-kind { margin-left: auto; display: inline-flex; align-items: center; gap: 5px; }
  .d-kind svg { width: 13px; height: 13px; }
  .d-close { display: none; }
  .detail h2 {
    font-family: var(--display); font-size: 30px; font-weight: 600; line-height: 1.1;
    letter-spacing: -0.02em; margin: 0 0 10px; text-wrap: balance;
  }
  .d-do { font-size: 17px; font-weight: 500; margin: 0 0 4px; line-height: 1.4; }
  .d-benefit { color: var(--accent); font-size: 15.5px; margin: 0 0 18px; }
  .d-origin {
    font-family: var(--mono); font-size: 12.5px; line-height: 1.6; color: var(--muted);
    border-left: 2px solid var(--line); padding: 2px 0 2px 13px; margin: 0 0 18px;
  }
  .d-block { border-top: 1px solid var(--line-soft); padding-top: 15px; margin-bottom: 15px; }
  .d-block h3 {
    font-family: var(--mono); font-size: 11px; font-weight: 500; text-transform: uppercase;
    letter-spacing: 0.09em; color: var(--faint); margin: 0 0 9px;
  }
  .d-block p { margin: 0; line-height: 1.55; color: var(--muted); }
  .d-block ul { margin: 0; padding-left: 17px; }
  .d-block li { margin-bottom: 5px; line-height: 1.5; }
  .d-block.avoid li { color: var(--warn); }
  /* Links, not pills. Pills mean "you can press this" everywhere else. */
  .d-links { display: flex; flex-direction: column; align-items: flex-start; gap: 6px; }
  .d-links a {
    font-size: 13.5px; color: var(--accent); text-decoration: underline;
    text-underline-offset: 3px; text-decoration-color: var(--line);
    transition: text-decoration-color .13s;
  }
  .d-links a:hover { text-decoration-color: var(--accent); }

  .ladder { border-top: 1px solid var(--line-soft); padding-top: 16px; margin-bottom: 16px; }
  .ladder .lab {
    font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.09em;
    color: var(--faint); display: block; margin-bottom: 9px;
  }
  .rungs { display: flex; flex-direction: column; gap: 5px; }
  .rung {
    display: flex; gap: 11px; align-items: baseline; text-align: left; width: 100%;
    padding: 7px 11px; border-radius: 8px; border: 1px solid var(--line-soft);
    transition: border-color .13s, background .13s;
  }
  .rung:hover { border-color: var(--line); background: var(--paper); }
  .rung.here { border-color: var(--accent); background: var(--accent-soft); }
  .rung-tier {
    font-family: var(--mono); font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.07em;
    color: var(--faint); flex: 0 0 74px;
  }
  .rung.here .rung-tier { color: var(--accent); }
  .rung-bar { font-size: 13px; line-height: 1.4; }

  footer { border-top: 1px solid var(--line); padding: 30px 0 60px; color: var(--muted); font-size: 13.5px; }
  footer a { color: var(--accent); }
  footer p { margin: 0 0 7px; max-width: 68ch; }
  .foot-brand { display: flex; align-items: flex-start; justify-content: space-between; gap: 32px; margin-top: 25px; padding-top: 24px; border-top: 1px solid var(--line-soft); }
  .foot-brand strong { display: block; color: var(--ink); font-size: 14px; font-weight: 600; }
  .foot-brand strong a { color: inherit; text-decoration: none; }
  .foot-brand strong a:hover { color: var(--accent); }
  .foot-brand span { display: block; max-width: 52ch; margin-top: 4px; }

  /* ── responsive ───────────────────────────────────────────── */
  @media (max-width: 900px) {
    .wrap { padding: 0 20px; }
    .owner-in { min-height: 48px; }
    .owner-cta { font-size: 12.5px; }
    .mast { padding: 46px 0 26px; }
    .panes { grid-template-columns: 1fr; gap: 0; padding-bottom: 40px; }
    .tally { margin-left: 0; }
    .pane {
      position: fixed; inset: 0; z-index: 60; border-radius: 0; border: 0;
      max-height: none; height: 100dvh; padding: 20px 20px 60px; display: none;
    }
    body.open .pane { display: block; }
    body.open { overflow: hidden; }
    .d-close {
      display: inline-block; margin-left: auto; font-family: var(--mono); font-size: 12px;
      color: var(--accent); padding: 4px 10px; border: 1px solid var(--line); border-radius: 999px;
    }
    .d-kind { margin-left: 0; }
    .foot-brand { display: block; }
  }
  @media (prefers-reduced-motion: reduce) {
    * { transition: none !important; animation: none !important; scroll-behavior: auto !important; }
  }
</style>
</head>
<body>
<nav class="owner" aria-label="Aescle">
  <div class="wrap owner-in">
    <a class="owner-mark" href="https://aescle.com" aria-label="Aescle home">
      <svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><circle cx="16" cy="16" r="11" stroke="currentColor" stroke-width="1.4" opacity=".5"/><circle cx="25.5" cy="10.5" r="3.05" fill="currentColor"/></svg>
      <b>AESCLE</b>
    </a>
    <a class="owner-cta" href="https://aescle.com/?beta=1">Personalize your protocols →</a>
  </div>
</nav>
<div class="wrap">
  <header class="mast">
    <h1>Productivity Protocols</h1>
    <p class="lede">Behaviors you can implement to do better work, across focus, sleep, exercise, nutrition, and calendar.</p>
    <div class="evidence-mix">
      <div class="mix-top"><b>${total}</b> protocols, by how much proof is behind them</div>
      <div class="dist" role="img" aria-label="${GRADES.map((g) => `${counts[g]} ${g}`).join(", ")}">${dist}</div>
      <div class="dist-key">${distKey}</div>
    </div>
    <p class="use">
      <code>npx -y productivity-protocols</code>
      <a href="https://github.com/aescle/productivity-protocols">${GH_ICON}<span>Source and data</span></a>
    </p>
  </header>
</div>

<div class="tools">
  <div class="wrap tools-in">
    <input class="search" id="q" type="search" placeholder="Search behaviors, triggers, people..." aria-label="Search protocols">
    <div class="grades" id="grades" role="group" aria-label="Evidence">
      <span class="glabel">Proof</span>
      ${GRADES.map(
        (g) =>
          `<button data-grade="${g}" aria-pressed="false"><i class="seg-${g}"></i>${g}</button>`,
      ).join("")}
    </div>
    <div class="areas" id="areas" role="group" aria-label="Filters">
      <div class="chip-row">
        <span class="grp"></span>
        <button id="essential" class="is-essential" aria-pressed="false">${STAR_ICON}<span>Essentials</span></button>
      </div>
      <div class="chip-row">
        <span class="grp">Work</span>
        ${kinds
          .filter((k) => KIND_GROUP[k] === "work")
          .map(
            (k) =>
              `<button data-kind="${esc(k)}" aria-pressed="false">${ICONS[k] ?? ""}<span>${esc(KIND_LABEL[k] ?? k)}</span><b>${byKind.get(k).length}</b></button>`,
          )
          .join("")}
      </div>
      <div class="chip-row">
        <span class="grp">Body</span>
        ${kinds
          .filter((k) => KIND_GROUP[k] !== "work")
          .map(
            (k) =>
              `<button data-kind="${esc(k)}" aria-pressed="false">${ICONS[k] ?? ""}<span>${esc(KIND_LABEL[k] ?? k)}</span><b>${byKind.get(k).length}</b></button>`,
          )
          .join("")}
      </div>
    </div>
    <span class="tally" id="tally">${protocols.length} shown</span>
  </div>
</div>

<div class="wrap">
  <div class="panes">
    <div class="list" id="list" role="listbox" aria-label="Protocols" tabindex="0">
      ${list}
      <p class="empty" id="empty" hidden>Nothing matches that. <b>Clear a filter</b> or change the search.</p>
    </div>
    <div class="pane" id="pane">
      ${protocols.map(detail).join("")}
    </div>
  </div>
</div>

<div class="wrap">
  <footer>
    <p>Not medical advice. These describe general practices and the evidence behind them, not recommendations for you specifically. Read the "skip it when" notes and talk to a doctor before changing anything that touches a medical condition or medication.</p>
    <p>Data is CC BY 4.0 and code is MIT. <a href="https://github.com/aescle/productivity-protocols">Contribute a protocol</a>.</p>
    <div class="foot-brand">
      <div><strong>Built and maintained by <a href="https://aescle.com">Aescle</a>.</strong><span>Aescle connects protocols to your own health and work patterns, then helps you act at the right time.</span></div>
    </div>
  </footer>
</div>

<script>
(function () {
  var rows = [].slice.call(document.querySelectorAll(".row"));
  var areas = [].slice.call(document.querySelectorAll(".area"));
  var q = document.getElementById("q");
  var tally = document.getElementById("tally");
  var empty = document.getElementById("empty");
  var pane = document.getElementById("pane");
  var state = { q: "", grades: {}, kinds: {}, essential: false };
  var current = null;

  function visible() { return rows.filter(function (r) { return !r.classList.contains("hide"); }); }

  function select(id, scroll) {
    var row = document.getElementById("r-" + id);
    var det = document.getElementById("d-" + id);
    if (!row || !det) return;
    if (current) {
      var prev = document.getElementById("r-" + current);
      var prevD = document.getElementById("d-" + current);
      if (prev) prev.setAttribute("aria-selected", "false");
      if (prevD) prevD.hidden = true;
    }
    current = id;
    row.setAttribute("aria-selected", "true");
    det.hidden = false;
    pane.scrollTop = 0;
    document.body.classList.add("open");
    if (scroll) row.scrollIntoView({ block: "nearest" });
    if (history.replaceState) history.replaceState(null, "", "#" + id);
  }

  function close() {
    document.body.classList.remove("open");
  }

  function apply() {
    var grades = Object.keys(state.grades).filter(function (g) { return state.grades[g]; });
    var picked = Object.keys(state.kinds).filter(function (k) { return state.kinds[k]; });
    var shown = 0;
    rows.forEach(function (r) {
      var ok = (grades.length === 0 || grades.indexOf(r.dataset.grade) !== -1)
        && (!state.essential || r.dataset.essential === "1")
        && (picked.length === 0 || picked.indexOf(r.dataset.kind) !== -1)
        && (!state.q || r.dataset.hay.indexOf(state.q) !== -1);
      r.classList.toggle("hide", !ok);
      if (ok) shown++;
    });
    areas.forEach(function (a) {
      a.classList.toggle("hide", !a.querySelector(".row:not(.hide)"));
    });
    tally.textContent = shown === rows.length ? shown + " shown" : shown + " of " + rows.length;
    empty.hidden = shown !== 0;
    // Keep the open protocol honest: if it filtered out, move to the first match.
    if (shown && current) {
      var cur = document.getElementById("r-" + current);
      if (cur && cur.classList.contains("hide")) select(visible()[0].dataset.id, false);
    }
  }

  q.addEventListener("input", function () { state.q = q.value.trim().toLowerCase(); apply(); });

  document.getElementById("grades").addEventListener("click", function (e) {
    var b = e.target.closest("button[data-grade]");
    if (!b) return;
    var g = b.dataset.grade;
    state.grades[g] = !state.grades[g];
    b.setAttribute("aria-pressed", String(!!state.grades[g]));
    apply();
  });

  document.getElementById("essential").addEventListener("click", function () {
    state.essential = !state.essential;
    this.setAttribute("aria-pressed", String(state.essential));
    apply();
  });

  document.getElementById("areas").addEventListener("click", function (e) {
    var b = e.target.closest("button[data-kind]");
    if (!b) return;
    var k = b.dataset.kind;
    state.kinds[k] = !state.kinds[k];
    b.setAttribute("aria-pressed", String(!!state.kinds[k]));
    apply();
  });

  document.getElementById("list").addEventListener("click", function (e) {
    var r = e.target.closest(".row");
    if (r) select(r.dataset.id, false);
  });

  pane.addEventListener("click", function (e) {
    if (e.target.closest("[data-close]")) return close();
    var g = e.target.closest("[data-goto]");
    if (g) select(g.dataset.goto, true);
  });

  // Arrow keys walk the visible list, so 227 can be reviewed without the mouse.
  document.addEventListener("keydown", function (e) {
    if (e.key === "Escape") return close();
    if (e.target === q || e.metaKey || e.ctrlKey || e.altKey) return;
    if (e.key !== "ArrowDown" && e.key !== "ArrowUp" && e.key !== "j" && e.key !== "k") return;
    var vis = visible();
    if (!vis.length) return;
    e.preventDefault();
    var down = e.key === "ArrowDown" || e.key === "j";
    var at = current ? vis.map(function (r) { return r.dataset.id; }).indexOf(current) : -1;
    var next = at === -1 ? 0 : Math.min(vis.length - 1, Math.max(0, at + (down ? 1 : -1)));
    select(vis[next].dataset.id, true);
  });

  var tools = document.querySelector(".tools");
  function stick() {
    document.documentElement.style.setProperty("--stick", (tools.offsetHeight + 16) + "px");
  }
  stick();
  window.addEventListener("resize", stick);
  if (document.fonts && document.fonts.ready) document.fonts.ready.then(stick);

  apply();
  var deep = location.hash.slice(1);
  if (deep && document.getElementById("d-" + deep)) select(deep, true);
  else { select(rows[0].dataset.id, false); close(); }
})();
</script>
</body>
</html>
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const outDir = path.join(pkgRoot, "site");
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, "index.html"), await renderSite());
  console.log("wrote site/index.html");
}
