// Regenerates src/protocols.generated.js from data/protocols/*.json.
// The mirror exists so app bundlers and Node consume one plain-JS module
// instead of importing dozens of JSON files. Run after editing any data file:
//
//   node packages/protocol-bank/scripts/generate-index.mjs
//
// scripts/validate.mjs fails when the committed mirror drifts from the data.
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

export async function renderGeneratedModule() {
  const dataDir = process.env.PROTOCOL_DATA_DIR ?? path.join(pkgRoot, "data", "protocols");
  const files = (await readdir(dataDir)).filter((f) => f.endsWith(".json")).sort();
  const protocols = [];
  for (const file of files) {
    protocols.push(JSON.parse(await readFile(path.join(dataDir, file), "utf8")));
  }
  return [
    "// @generated by scripts/generate-index.mjs — do not edit.",
    "// Source of truth: data/protocols/*.json (one file per protocol).",
    `export const PROTOCOLS = ${JSON.stringify(protocols, null, 2)};`,
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const outPath = path.join(pkgRoot, "src", "protocols.generated.js");
  await writeFile(outPath, await renderGeneratedModule());
  console.log(`wrote ${path.relative(process.cwd(), outPath)}`);
  const { renderSite } = await import("./generate-site.mjs");
  const sitePath = path.join(pkgRoot, "site", "index.html");
  await (await import("node:fs/promises")).mkdir(path.dirname(sitePath), { recursive: true });
  await writeFile(sitePath, await renderSite());
  console.log(`wrote ${path.relative(process.cwd(), sitePath)}`);
}
