// Renders site/index.html — the public browse page for the bank — from
// data/protocols/*.json. Deterministic; regenerated by generate-index.mjs and
// drift-checked by validate.mjs:
//
//   node packages/protocol-bank/scripts/generate-index.mjs
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

const KIND_LABEL = {
  calendar_defense: "Calendar", deep_work: "Focus", nutrition: "Nutrition", recovery: "Recovery",
  sleep: "Sleep", social: "Social", training: "Training", walk: "Movement",
};
const FAMILY_LABEL = {
  attention_defense: "Focus defense", daily_activity: "Daily activity", aerobic_volume: "Aerobic volume",
  strength_capacity: "Strength", sleep_regularity: "Sleep rhythm", sleep_shutdown: "Screen shutdown",
  calendar_defense: "Calendar defense", meal_timing: "Meal timing", eating_window: "Eating window",
  heat_exposure: "Heat exposure", cold_exposure: "Cold exposure", mindfulness: "Mindfulness",
};
const TIER_ORDER = { beginner: 0, intermediate: 1, advanced: 2 };

const esc = (s) =>
  String(s).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

export async function renderSite() {
  const dataDir = path.join(pkgRoot, "data", "protocols");
  const files = (await readdir(dataDir)).filter((f) => f.endsWith(".json")).sort();
  const protocols = [];
  for (const f of files) protocols.push(JSON.parse(await readFile(path.join(dataDir, f), "utf8")));

  const families = new Map();
  const standalone = [];
  for (const p of protocols) {
    if (p.family) {
      if (!families.has(p.family)) families.set(p.family, []);
      families.get(p.family).push(p);
    } else standalone.push(p);
  }
  for (const list of families.values()) list.sort((a, b) => TIER_ORDER[a.tier] - TIER_ORDER[b.tier]);
  const familyOrder = [...families.keys()].sort((a, b) =>
    (FAMILY_LABEL[a] ?? a).localeCompare(FAMILY_LABEL[b] ?? b));
  const kinds = [...new Set(standalone.map((p) => p.kind))].sort((a, b) =>
    (KIND_LABEL[a] ?? a).localeCompare(KIND_LABEL[b] ?? b));

  const gradeCount = { strong: 0, moderate: 0, emerging: 0, anecdotal: 0 };
  for (const p of protocols) gradeCount[p.evidence.grade] += 1;

  const card = (p) => {
    const g = p.evidence.grade;
    const hay = esc(
      [p.id, p.name, p.title, p.benefit, p.rationale, ...(p.targets ?? []), ...(p.indications ?? [])]
        .join(" ")
        .toLowerCase(),
    );
    return `
  <details class="card" data-grade="${g}" data-hay="${hay}">
    <summary>
      <div class="card-top">
        <h3>${esc(p.name)}</h3>
        <span class="chip grade grade-${g}">${g}</span>
        ${p.tier ? `<span class="tiertxt">${esc(p.tier)}</span>` : ""}
      </div>
      <p class="benefit">${esc(p.benefit)}</p>
      <p class="how">${esc(p.title)}</p>
    </summary>
    <div class="detail">
      <p class="rationale">${esc(p.rationale)}</p>
      ${p.origin ? `<p class="origin">${esc(p.origin)}</p>` : ""}
      <div class="block">
        <span class="blabel">When to use</span>
        <ul>${(p.indications ?? []).map((i) => `<li>${esc(i)}</li>`).join("")}</ul>
      </div>
      ${p.tierTarget ? `<p class="tier-target">Target: ${esc(p.tierTarget)}</p>` : ""}
      ${p.avoidWhen ? `<p class="avoid">Avoid: ${p.avoidWhen.map(esc).join(" ")}</p>` : ""}
      <p class="evidence">${esc(p.evidence.summary)}</p>
      <p class="links">
        ${p.evidence.sources.map((s) => `<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)}</a>`).join(" · ")}
        ${p.guide ? ` · <a class="guide" href="${esc(p.guide.url)}" target="_blank" rel="noopener">Guide: ${esc(p.guide.source)}</a>` : ""}
        <span class="pid">${esc(p.id)}</span>
      </p>
    </div>
  </details>`;
  };

  const section = (id, label, sub, list) => `
  <section class="family" id="${esc(id)}">
    <header class="fam-head">
      <h2>${esc(label)}</h2>
      <span class="fam-sub">${esc(sub)}</span>
    </header>
    <div class="cards">${list.map(card).join("")}</div>
  </section>`;

  const familySections = familyOrder
    .map((f) => section(f, FAMILY_LABEL[f] ?? f, "ladder · beginner → advanced", families.get(f)))
    .join("");
  const standaloneSections = kinds
    .map((k) =>
      section(`kind-${k}`, KIND_LABEL[k] ?? k, "standalone",
        standalone.filter((p) => p.kind === k).sort((a, b) => a.id.localeCompare(b.id))))
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Protocol Bank</title>
<meta name="description" content="An open, evidence-graded bank of health and performance protocols: behaviors, triggers, progressions, and citations.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>
  :root {
    --ground: #f6f7f5; --surface: #ffffff; --ink: #182019; --muted: #5c665e;
    --line: #e3e7e2; --accent: #0e7c66; --accent-soft: #e2f0ec;
    --strong: #0e7c66; --strong-bg: #e2f0ec;
    --moderate: #3b6fa0; --moderate-bg: #e7eef5;
    --emerging: #a1580a; --emerging-bg: #f7ecdd;
    --anecdotal: #616a75; --anecdotal-bg: #eceef1;
    --avoid: #a03b3b;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --ground: #151815; --surface: #1d211d; --ink: #e8ece8; --muted: #9aa59c;
      --line: #2c322c; --accent: #4dbfa4; --accent-soft: #1d3a32;
      --strong: #4dbfa4; --strong-bg: #1d3a32;
      --moderate: #7fa8d0; --moderate-bg: #22303f;
      --emerging: #d99a4e; --emerging-bg: #3a2c1a;
      --anecdotal: #98a1ac; --anecdotal-bg: #272c33;
      --avoid: #d08080;
    }
  }
  :root[data-theme="dark"] {
    --ground: #151815; --surface: #1d211d; --ink: #e8ece8; --muted: #9aa59c;
    --line: #2c322c; --accent: #4dbfa4; --accent-soft: #1d3a32;
    --strong: #4dbfa4; --strong-bg: #1d3a32;
    --moderate: #7fa8d0; --moderate-bg: #22303f;
    --emerging: #d99a4e; --emerging-bg: #3a2c1a;
    --anecdotal: #98a1ac; --anecdotal-bg: #272c33;
    --avoid: #d08080;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--ground); color: var(--ink);
    font-family: "Instrument Sans", "Helvetica Neue", Arial, sans-serif;
    font-size: 15px; line-height: 1.5;
  }
  .wrap { max-width: 1060px; margin: 0 auto; padding: 0 24px 40px; }
  .masthead { padding: 44px 0 20px; }
  .masthead h1 { margin: 0 0 6px; font-size: 30px; font-weight: 650; letter-spacing: -0.02em; text-wrap: balance; }
  .masthead p { margin: 0; color: var(--muted); max-width: 62ch; }
  .stats { display: flex; flex-wrap: wrap; gap: 24px; margin-top: 18px; }
  .stat { display: flex; flex-direction: column; }
  .stat b { font-family: "IBM Plex Mono", ui-monospace, Menlo, monospace; font-size: 21px; font-weight: 500; font-variant-numeric: tabular-nums; }
  .stat span { font-size: 12px; text-transform: uppercase; letter-spacing: 0.07em; color: var(--muted); }
  .bar {
    position: sticky; top: 0; z-index: 5; background: var(--ground);
    border-bottom: 1px solid var(--line); padding: 12px 0; margin-bottom: 28px;
    display: flex; flex-wrap: wrap; gap: 10px; align-items: center;
  }
  .bar input[type="search"] {
    flex: 1 1 220px; min-width: 180px; padding: 8px 12px; border: 1px solid var(--line);
    border-radius: 8px; background: var(--surface); color: var(--ink); font: inherit;
  }
  .bar input[type="search"]:focus { outline: 2px solid var(--accent); outline-offset: 1px; }
  .fbtn {
    border: 1px solid var(--line); background: var(--surface); color: var(--muted);
    font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 12.5px;
    padding: 6px 11px; border-radius: 999px; cursor: pointer;
  }
  .fbtn[aria-pressed="true"] { color: var(--ink); border-color: var(--accent); background: var(--accent-soft); }
  .fbtn:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
  .count-note { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 12.5px; color: var(--muted); margin-left: auto; }
  .family { margin-bottom: 34px; }
  .fam-head { display: flex; align-items: baseline; gap: 12px; border-bottom: 1px solid var(--line); padding-bottom: 6px; margin-bottom: 14px; }
  .fam-head h2 { margin: 0; font-size: 17px; font-weight: 650; letter-spacing: -0.01em; }
  .fam-sub { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 12px; color: var(--muted); }
  .cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(310px, 1fr)); gap: 14px; }
  .card { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 0; }
  .card.hide { display: none; }
  .card > summary { list-style: none; cursor: pointer; padding: 13px 16px; display: flex; flex-direction: column; gap: 4px; position: relative; }
  .card > summary::-webkit-details-marker { display: none; }
  .card > summary::after { content: "+"; position: absolute; top: 10px; right: 14px; color: var(--muted); font-family: "IBM Plex Mono", ui-monospace, monospace; }
  .card[open] > summary::after { content: "2"; }
  .card > summary:focus-visible { outline: 2px solid var(--accent); outline-offset: -2px; border-radius: 10px; }
  .card-top { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; padding-right: 18px; }
  .card h3 { margin: 0; font-size: 15.5px; font-weight: 650; letter-spacing: -0.01em; }
  .chip { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 10.5px; letter-spacing: 0.04em; padding: 1px 7px; border-radius: 999px; }
  .grade-strong { color: var(--strong); background: var(--strong-bg); }
  .grade-moderate { color: var(--moderate); background: var(--moderate-bg); }
  .grade-emerging { color: var(--emerging); background: var(--emerging-bg); }
  .grade-anecdotal { color: var(--anecdotal); background: var(--anecdotal-bg); }
  .tiertxt { font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 10.5px; color: var(--muted); }
  .benefit { margin: 0; color: var(--accent); font-weight: 550; }
  .how { margin: 0; color: var(--muted); font-size: 13.5px; }
  .detail { padding: 0 16px 14px; display: flex; flex-direction: column; gap: 8px; border-top: 1px dashed var(--line); }
  .detail > :first-child { margin-top: 10px; }
  .rationale { margin: 0; color: var(--muted); font-size: 13px; }
  .origin { margin: 0; color: var(--muted); font-size: 12.5px; font-style: italic; }
  .block .blabel { display: block; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); margin-bottom: 3px; }
  .block ul { margin: 0; padding-left: 18px; }
  .block li { margin: 2px 0; }
  .tier-target { margin: 0; font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 12px; color: var(--accent); }
  .avoid { margin: 0; font-size: 13px; color: var(--avoid); }
  .evidence { margin: 0; font-size: 13px; color: var(--muted); }
  .links { margin: 0; font-size: 12.5px; }
  .links a { color: var(--moderate); text-decoration: none; }
  .links a.guide { color: var(--accent); }
  .links a:hover, .links a:focus-visible { text-decoration: underline; }
  .pid { float: right; font-family: "IBM Plex Mono", ui-monospace, monospace; font-size: 11px; color: var(--muted); }
  footer { border-top: 1px solid var(--line); margin-top: 20px; padding: 18px 0 30px; color: var(--muted); font-size: 13px; }
  footer a { color: var(--accent); text-decoration: none; }
  footer a:hover, footer a:focus-visible { text-decoration: underline; }
</style>
</head>
<body>
<div class="wrap">
  <header class="masthead">
    <h1>Protocol Bank</h1>
    <p>An open, evidence-graded bank of health and performance protocols for people who optimize
    their focus, energy, and long arc like they optimize systems. Each protocol is a concrete
    behavior with the signals that indicate trying it, an honest evidence grade, citations, and
    contraindications — structured data your agent can act on.</p>
    <div class="stats">
      <div class="stat"><b>${protocols.length}</b><span>protocols</span></div>
      <div class="stat"><b>${families.size}</b><span>ladders</span></div>
      <div class="stat"><b>${gradeCount.strong}·${gradeCount.moderate}·${gradeCount.emerging}·${gradeCount.anecdotal}</b><span>strong · mod · emer · anec</span></div>
    </div>
  </header>

  <div class="bar">
    <input id="q" type="search" placeholder="Search titles, triggers, targets…" aria-label="Search protocols">
    <button class="fbtn" data-grade="strong" aria-pressed="false">strong ${gradeCount.strong}</button>
    <button class="fbtn" data-grade="moderate" aria-pressed="false">moderate ${gradeCount.moderate}</button>
    <button class="fbtn" data-grade="emerging" aria-pressed="false">emerging ${gradeCount.emerging}</button>
    <button class="fbtn" data-grade="anecdotal" aria-pressed="false">anecdotal ${gradeCount.anecdotal}</button>
    <span class="count-note" id="count"></span>
  </div>

  ${familySections}
  ${standaloneSections}

  <footer>
    Maintained by <a href="https://aescle.com" rel="noopener">Aescle</a> · Data CC BY 4.0 · Code MIT ·
    Not medical advice: protocols describe general practices and their evidence, not recommendations
    for any individual.
  </footer>
</div>
<script>
  const cards = [...document.querySelectorAll(".card")];
  const q = document.getElementById("q");
  const count = document.getElementById("count");
  const gradeBtns = [...document.querySelectorAll("button[data-grade]")];
  const active = { grades: new Set(), q: "" };
  function apply() {
    let shown = 0;
    for (const c of cards) {
      const okGrade = active.grades.size === 0 || active.grades.has(c.dataset.grade);
      const okQ = !active.q || c.dataset.hay.includes(active.q);
      const ok = okGrade && okQ;
      c.classList.toggle("hide", !ok);
      if (ok) shown++;
    }
    for (const s of document.querySelectorAll(".family")) {
      s.style.display = s.querySelector(".card:not(.hide)") ? "" : "none";
    }
    count.textContent = shown + " / " + cards.length;
  }
  q.addEventListener("input", () => { active.q = q.value.trim().toLowerCase(); apply(); });
  for (const b of gradeBtns) b.addEventListener("click", () => {
    const g = b.dataset.grade;
    if (active.grades.has(g)) active.grades.delete(g); else active.grades.add(g);
    b.setAttribute("aria-pressed", String(active.grades.has(g)));
    apply();
  });
  apply();
</script>
</body>
</html>
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const outDir = path.join(pkgRoot, "site");
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, "index.html"), await renderSite());
  console.log("wrote site/index.html");
}
